title: Cayman Blog Theme
description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and GitHub Pages, with social features.
show_downloads: true
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Lore Pirri"
featured_image: /thumbnail-jumbo.png
twitter:
  username: lorepirri
#  site:
facebook:
  publisher: lorepirri
  profile_id: 1809805629
  app_id: 1798910940422432
#  admins:
