title: 테디노트
description: 모두를 위한 데이터 사이언스 글 저장소입니다. 데이터 분석, 머신러닝, 딥러닝 등 데이터 사이언스의 대중화를 꿈 꿉니다. 모두가 인공지능을 마스터 하는 그 날까지. 데이터 분석, 머신러닝, 딥러닝 등 지식 공유에 참여하고 싶습니다.

url:   https://teddylee777.github.io
image: /images/logo.png

show_downloads: false
future:         true
# timezone:       Asia/Seoul

cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

permalink: /:categories/:title

# social
author: Teddy Lee
disqus_shortname:   teddylee777
google_analytics:   UA-111508093-1

repository: teddylee777/teddylee777.github.io

highlighter: rouge
markdown:    kramdown

# root_dir: http://localhost:4000
category_dir: categories/
tag_dir: tag/
categories: [android, aws, data_science, git, jekyll, linux, machine-learning, python, pytorch, review, synology, thoughts]

paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

